
image: alpine:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TERRAFORM_VERSION: "0.14.5"
  TF_DOCS_VERSION: "v0.10.1"
  TF_IN_AUTOMATION: "TRUE"
  TEST_DIR: "${CI_PROJECT_DIR}/test/src"

stages:
  - pre-checks
  - test
  - release

precommit:
  stage: pre-checks
  image: python:buster
  script:
    - apt-get update
    - apt-get install -y shellcheck
    - curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
    - tfswitch ${TERRAFORM_VERSION}
    - TF_DOCS="terraform-docs-${TF_DOCS_VERSION}-linux-amd64"
    - curl -Lo ./terraform-docs https://github.com/terraform-docs/terraform-docs/releases/download/${TF_DOCS_VERSION}/${TF_DOCS}
    - chmod +x  ./terraform-docs
    - mv ./terraform-docs /usr/bin/terraform-docs 
    - pip3 install pre-commit
    - pre-commit run --all-files

security-check:
  stage: pre-checks
  image: python:alpine
  before_script:
    - pip3 install --upgrade pip && pip3 install --upgrade setuptools
  script:
    - pip3 install checkov
    - checkov -d .

release:
  image: node:13
  stage: release
  script:
    - npm install @semantic-release/gitlab @semantic-release/exec
    - npx semantic-release
  only:
    refs:
    - master

    - npm install @semantic-release/gitlab @semantic-release/exec
    - npx semantic-release
  only:
    refs:
    - master
